### ISSUE TITLE
Search for Zonal Statistics for Multiband Rasters have no any results.

### ISSUE THREAD

**Issue by xiaoenli4816** [dymaxionlabs/qgis-zonal-statistics-multiband#2]
Search for Zonal Statistics for Multiband Rasters have no any results.

**Comment by greenguy33** [comment]
@xiaoenli4816 This is not even close to being descriptive enough for anybody to be able to possibly help you with your problem

**Comment by HarrySimmonsPhD** [comment]
@xiaoenli4816 when you follow Plugins > manage and install plugins > Settings > Check the box that says "Show also Experimental Plugins". Then you should be able to see the zonal statistics for multiband raster plugin in "All"

**Comment by xiaoenli4816** [comment]
Thank you for your suggestion, there still have some wrong, Couldn't load plugin 'zonal_exact' due to an error when calling its classFactory() method 

ModuleNotFoundError: No module named 'exactextract' 
Traceback (most recent call last):
  File "D:\Program Files/QGIS 3.36.0/apps/qgis/./python\qgis\utils.py", line 426, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:\Users/DELL/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\zonal_exact\__init__.py", line 35, in classFactory
    from .zonal_exact import ZonalExact
  File "D:\Program Files/QGIS 3.36.0/apps/qgis/./python\qgis\utils.py", line 923, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/DELL/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\zonal_exact\zonal_exact.py", line 32, in 
    from .zonal_exact_dialog import ZonalExactDialog
  File "D:\Program Files/QGIS 3.36.0/apps/qgis/./python\qgis\utils.py", line 923, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/DELL/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\zonal_exact\zonal_exact_dialog.py", line 39, in 
    from .task_classes import CalculateStatsTask, MergeStatsTask
  File "D:\Program Files/QGIS 3.36.0/apps/qgis/./python\qgis\utils.py", line 923, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/DELL/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\zonal_exact\task_classes.py", line 1, in 
    from exactextract import exact_extract
  File "D:\Program Files/QGIS 3.36.0/apps/qgis/./python\qgis\utils.py", line 923, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'exactextract'


Python version: 3.9.18 (heads/master:5eba59e, Feb  1 2024, 20:02:10) [MSC v.1929 64 bit (AMD64)] 
QGIS version: 3.36.0-Maidenhead Maidenhead, 09951dc0 

Python Path:
D:/Program Files/QGIS 3.36.0/apps/qgis/./python
C:/Users/DELL/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/DELL/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
D:/Program Files/QGIS 3.36.0/apps/qgis/./python/plugins
D:\Program Files\QGIS 3.36.0\apps\grass\grass83\etc\python
C:\Users\DELL\Documents
D:\Program Files\QGIS 3.36.0\bin\python39.zip
D:\Program Files\QGIS 3.36.0\apps\Python39\DLLs
D:\Program Files\QGIS 3.36.0\apps\Python39\lib
D:\Program Files\QGIS 3.36.0\bin
D:\Program Files\QGIS 3.36.0\apps\Python39
D:\Program Files\QGIS 3.36.0\apps\Python39\lib\site-packages
D:\Program Files\QGIS 3.36.0\apps\Python39\lib\site-packages\win32
D:\Program Files\QGIS 3.36.0\apps\Python39\lib\site-packages\win32\lib
D:\Program Files\QGIS 3.36.0\apps\Python39\lib\site-packages\Pythonwin
C:/Users/DELL/AppData/Roaming/QGIS/QGIS3\profiles\default/python
